apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mlzoomcamp-eks-123
  region: us-east-1
  #version: "1.34"

nodeGroups:
  - name: ng-t3-small
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 1